services:
  stream-server:
    build: .
    container_name: mv-streaming
    ports:
      - "1935:1935" # RTMP Ingest from OBS
      - "80:80" # HTTP for Web/HLS
      - "443:443" # HTTPS
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /tmp/hls:/tmp/hls
      - /etc/letsencrypt:/etc/letsencrypt:ro
