services:
  stream-server:
    build: .
    container_name: professional_stream_server
    ports:
      - "1935:1935" # RTMP Ingest from OBS
      - "80:80" # HTTP for Web/HLS
      - "443:443" # HTTPS
    restart: always
